package com.infinitus.hcp.events;

import com.infinitus.hcp.config.ApplicationConfig;
import com.infinitus.hcp.model.HCPError;

import java.util.Map;

/**
 * Created by M on 16/9/9.
 * <p/>
 * Base class for events, that generated by installation/download workers.
 *
 * @see com.infinitus.hcp.updater.InstallationWorker
 * @see com.infinitus.hcp.updater.UpdateLoaderWorker
 * @see HCPEvent
 */
public class WorkerEvent extends HCPEventImpl {

    private static final String CONFIG_KEY = "config";

    /**
     * Class constructor
     *
     * @param eventName string identifier of the event
     * @param error     error information
     * @param appConfig application config which this worker used
     * @see HCPError
     * @see ApplicationConfig
     */
    protected WorkerEvent(String eventName, HCPError error, ApplicationConfig appConfig) {
        super(eventName, error);

        if (appConfig != null) {
            data().put(CONFIG_KEY, appConfig);
        }
    }

    /**
     * Getter for application config, attached to this event.
     * This config was used to perform download/installation work.
     *
     * @return application config
     */
    public ApplicationConfig applicationConfig() {
        final Map<String, Object> eventData = data();
        if (!eventData.containsKey(CONFIG_KEY)) {
            return null;
        }

        return (ApplicationConfig) eventData.get(CONFIG_KEY);
    }
}